version: "3.3"
volumes:
  mariadb:
  vendor:
services:
  db:
    image: mariadb:10.1.16
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=redmine
  app:
    build: .
    container_name: "railsdev"
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - "$PWD/redmine:/var/lib/redmine"
      - "$PWD/database.yml:/var/lib/redmine/config/database.yml"
      - vendor:/var/lib/redmine/vendor
    depends_on:
      - db
